### PR TITLE
Add kebab case

### LINKED ISSUE #16: Add kebab (dash) case command
**Is your feature request related to a problem? Please describe.**
At the moment camel, pascal and snake cases are available. Kebab case is another popular ways to combine strings and abbreviate doesn't provide this option.  

**Describe the solution you'd like**
It would be nice to have also the `kebab` command available that can be used to abbreviate a string and convert it to kebab case.

Example
```bash
$ abbreviate kebab StrategyLimited
stg-ltd
```

### PR DESCRIPTION
**Pull request by RiyaJohn**
# Description

Adding support for kebab case

Fixes #16

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Running existing tests
- [x] Created new tests

# Checklist:

- [ ] My code has been linted (`make lint`)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have rebased my branch to include the latest changes from `master`

### CODE REVIEW

**Comment by RiyaJohn** [comment]
@dnnrly Please review this PR

**Comment by dnnrly** [comment]
First of all, I want to say a massive thank you for putting this PR forward!

I've been looking at it and it looks like it solves the problem *exactly* as I specified in the issue. Unfortunately, it's made it obvious just how badly I messed up the description and asked for the wrong thing.

So my concern here is that we're only solving single specific cases but we have an opportunity to fix it generally, and better. I like that you renamed the function, and perhaps we can start there. What if it were renamed (again) to `AsSeparated`? Then we can keep the `snake` and `kebab` commands and add a new `separated` command that _requires_ a separator option.

I think the upshot of this is that we could remove the extra unit tests that you added to support kebab case. I think we can get rid of the additional test cases you added, I think these are already covered by the existing ones - I think I kind of half-arsed the implementation without thinking too much how the CLI would look.

How does that sound?

I think when all this is done, you've earned yourself a new follower on Twitter. 😄

**Comment by RiyaJohn** [comment]
> First of all, I want to say a massive thank you for putting this PR forward!
> 
> I've been looking at it and it looks like it solves the problem _exactly_ as I specified in the issue. Unfortunately, it's made it obvious just how badly I messed up the description and asked for the wrong thing.
> 
> So my concern here is that we're only solving single specific cases but we have an opportunity to fix it generally, and better. I like that you renamed the function, and perhaps we can start there. What if it were renamed (again) to `AsSeparated`? Then we can keep the `snake` and `kebab` commands and add a new `separated` command that _requires_ a separator option.
> 
> I think the upshot of this is that we could remove the extra unit tests that you added to support kebab case. I think we can get rid of the additional test cases you added, I think these are already covered by the existing ones - I think I kind of half-arsed the implementation without thinking too much how the CLI would look.
> 
> Once all that is done (it's not a massive job) we can add a couple of test cases to `acceptance.bats` to prove that we got the plumbing right.
> 
> How does that sound?
> 
> I think when all this is done, you've earned yourself a new follower on Twitter. 😄

This sounds good, I like it this way. I will make the changes

**Comment by RiyaJohn** [comment]
@dnnrly I made the changes, removed option for separator flag for snake and kebab commands. But let me know if we wanna retain it

**Pull request merged**
